//
//  Video.swift
//  Pangolin
//
//  Created by Matt Kevan on 16/08/2025.
//


// Models/VideoModel.swift
import Foundation
import CoreData
import AVFoundation

// MARK: - Core Data Extensions
// Base classes are auto-generated by Core Data from .xcdatamodeld

enum VideoWatchStatus: Int {
    case unwatched = 0
    case inProgress = 1
    case watched = 2

    var displayName: String {
        switch self {
        case .unwatched:
            return "Unwatched"
        case .inProgress:
            return "In Progress"
        case .watched:
            return "Watched"
        }
    }

    var systemImage: String {
        switch self {
        case .unwatched:
            return "circle"
        case .inProgress:
            return "clock.arrow.trianglehead.counterclockwise.rotate.90"
        case .watched:
            return "checkmark.circle.fill"
        }
    }
}

enum LibraryStoragePreference: String, CaseIterable, Identifiable {
    case keepAllDownloaded = "keep_all_downloaded"
    case optimizeStorage = "optimize_storage"

    var id: String { rawValue }

    var title: String {
        switch self {
        case .keepAllDownloaded:
            return "Keep All Downloaded"
        case .optimizeStorage:
            return "Offload to iCloud"
        }
    }

    var subtitle: String {
        switch self {
        case .keepAllDownloaded:
            return "Keep all videos available on this Mac."
        case .optimizeStorage:
            return "Store older videos in iCloud to reduce local disk usage."
        }
    }
}

// MARK: - Video Extensions
extension Video {
    // Computed properties
    var fileURL: URL? {
        if let cloudRelativePath, !cloudRelativePath.isEmpty,
           let ubiquitousRoot = FileManager.default.url(forUbiquityContainerIdentifier: "iCloud.com.newindustries.pangolin") {
            return ubiquitousRoot.appendingPathComponent(cloudRelativePath)
        }

        // Import staging fallback before cloudRelativePath is set.
        guard let library = library,
              let relativePath = relativePath,
              let libraryPath = library.url else { return nil }
        return libraryPath.appendingPathComponent("Videos").appendingPathComponent(relativePath)
    }
    
    func isVideoFileAccessible() async -> Bool {
        let status = await VideoFileManager.shared.isVideoFileAccessible(self)
        return status == .local
    }
    
    // Get video file status asynchronously
    func getVideoFileStatus() async -> VideoFileStatus {
        return await VideoFileManager.shared.isVideoFileAccessible(self)
    }
    
    // Get video file URL with iCloud download if needed
    func getAccessibleFileURL(downloadIfNeeded: Bool = true) async throws -> URL {
        return try await VideoFileManager.shared.getVideoFileURL(for: self, downloadIfNeeded: downloadIfNeeded)
    }
    
    var formattedDuration: String {
        let formatter = DateComponentsFormatter()
        formatter.allowedUnits = [.hour, .minute, .second]
        formatter.unitsStyle = .positional
        formatter.zeroFormattingBehavior = .pad
        return formatter.string(from: duration) ?? "00:00"
    }
    
    var hasSubtitles: Bool {
        return (subtitles?.count ?? 0) > 0
    }

    var watchProgress: Double {
        guard duration > 0 else { return 0 }
        let progress = playbackPosition / duration
        return min(max(progress, 0), 1)
    }

    var watchStatus: VideoWatchStatus {
        let progress = watchProgress
        if progress < 0.03 {
            return .unwatched
        }
        if progress < 0.90 {
            return .inProgress
        }
        return .watched
    }
    
    var thumbnailURL: URL? {
        guard let thumbnailPath = thumbnailPath else { return nil }
        if let ubiquitousRoot = FileManager.default.url(forUbiquityContainerIdentifier: VideoFileManager.shared.cloudContainerIdentifier) {
            let cloudURL = ubiquitousRoot.appendingPathComponent("Thumbnails").appendingPathComponent(thumbnailPath)
            if FileManager.default.fileExists(atPath: cloudURL.path) {
                return cloudURL
            }
        }
        guard let libraryPath = library?.url else { return nil }
        return libraryPath.appendingPathComponent("Thumbnails").appendingPathComponent(thumbnailPath)
    }
}

// MARK: - Folder Extensions
extension Folder {
    // Computed properties
    var isProject: Bool {
        isTopLevel && !isSmartFolder
    }

    var childFoldersArray: [Folder] {
        guard let children = childFolders else { return [] }
        return children.compactMap { $0 as? Folder }.sorted { 
            ($0.name ?? "").localizedCompare($1.name ?? "") == .orderedAscending 
        }
    }
    
    var videosArray: [Video] {
        guard let videos = videos else { return [] }
        return videos.compactMap { $0 as? Video }.sorted { 
            ($0.title ?? "").localizedCompare($1.title ?? "") == .orderedAscending 
        }
    }

    var sectionsArray: [Folder] {
        childFoldersArray
    }

    var resolvedProjectTitle: String {
        let trimmedTitle = projectTitle?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if !trimmedTitle.isEmpty {
            return trimmedTitle
        }

        let trimmedName = name?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return trimmedName.isEmpty ? "Untitled Project" : trimmedName
    }

    var resolvedProjectProvider: String {
        let trimmedProvider = projectProvider?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return trimmedProvider
    }

    var resolvedProjectThumbnailPath: String? {
        let trimmedPath = projectThumbnailPath?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if !trimmedPath.isEmpty {
            return trimmedPath
        }

        return firstDescendantThumbnailPath
    }

    var projectThumbnailURL: URL? {
        guard let thumbnailPath = resolvedProjectThumbnailPath else { return nil }
        if let ubiquitousRoot = FileManager.default.url(forUbiquityContainerIdentifier: VideoFileManager.shared.cloudContainerIdentifier) {
            let cloudURL = ubiquitousRoot.appendingPathComponent("Thumbnails").appendingPathComponent(thumbnailPath)
            if FileManager.default.fileExists(atPath: cloudURL.path) {
                return cloudURL
            }
        }
        guard let libraryPath = library?.url else { return nil }
        return libraryPath.appendingPathComponent("Thumbnails").appendingPathComponent(thumbnailPath)
    }
    
    var itemCount: Int {
        return (childFolders?.count ?? 0) + (videos?.count ?? 0)
    }
    
    var totalVideoCount: Int {
        let directVideos = videos?.count ?? 0
        let childVideos = childFolders?.reduce(into: 0) { result, folder in
            if let folder = folder as? Folder {
                result += folder.totalVideoCount
            }
        } ?? 0
        return directVideos + childVideos
    }

    private var firstDescendantThumbnailPath: String? {
        for video in videosArray {
            let trimmedPath = video.thumbnailPath?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            if !trimmedPath.isEmpty {
                return trimmedPath
            }
        }

        for childFolder in childFoldersArray {
            if let childThumbnailPath = childFolder.firstDescendantThumbnailPath {
                return childThumbnailPath
            }
        }

        return nil
    }
}

// MARK: - Subtitle Extensions
extension Subtitle {
    // Computed properties
    var fileURL: URL? {
        guard let relativePath = relativePath else { return nil }
        if let ubiquitousRoot = FileManager.default.url(forUbiquityContainerIdentifier: VideoFileManager.shared.cloudContainerIdentifier) {
            let cloudURL = ubiquitousRoot.appendingPathComponent("Subtitles").appendingPathComponent(relativePath)
            if FileManager.default.fileExists(atPath: cloudURL.path) {
                return cloudURL
            }
        }
        guard let video = video,
              let libraryPath = video.library?.url else { return nil }
        return libraryPath.appendingPathComponent("Subtitles").appendingPathComponent(relativePath)
    }
    
    var displayName: String {
        if let languageName = languageName {
            return languageName
        } else if let language = language {
            return Locale.current.localizedString(forLanguageCode: language) ?? language
        }
        return fileName ?? "Unknown Subtitle"
    }
}

// MARK: - Library Extensions
extension Library {
    static let defaultMaxLocalVideoCacheBytes: Int64 = 10 * 1024 * 1024 * 1024

    // Computed properties
    var url: URL? {
        guard let libraryPath = libraryPath else { return nil }
        return URL(fileURLWithPath: libraryPath)
    }

    var storagePreference: LibraryStoragePreference {
        get {
            guard let rawValue = videoStorageType,
                  let preference = LibraryStoragePreference(rawValue: rawValue) else {
                return .optimizeStorage
            }
            return preference
        }
        set {
            videoStorageType = newValue.rawValue
        }
    }

    var resolvedMaxLocalVideoCacheBytes: Int64 {
        max(maxLocalVideoCacheBytes, Library.defaultMaxLocalVideoCacheBytes)
    }

    var maxLocalCacheGB: Int {
        get {
            let bytesPerGB = Int64(1024 * 1024 * 1024)
            let gb = Int((resolvedMaxLocalVideoCacheBytes + bytesPerGB - 1) / bytesPerGB)
            return max(1, gb)
        }
        set {
            let bounded = max(1, newValue)
            maxLocalVideoCacheBytes = Int64(bounded) * Int64(1024 * 1024 * 1024)
        }
    }
    
    var videoCount: Int {
        return videos?.count ?? 0
    }
    
    var totalSize: Int64 {
        return videos?.reduce(into: 0) { result, video in
            if let video = video as? Video {
                result += video.fileSize
            }
        } ?? 0
    }
    
    var formattedSize: String {
        formattedByteCount(totalSize)
    }

    func formattedByteCount(_ byteCount: Int64) -> String {
        let formatter = ByteCountFormatter()
        formatter.countStyle = .file
        return formatter.string(fromByteCount: byteCount)
    }
}

// MARK: - Content Types
enum ContentType: Hashable {
    case folder(Folder)
    case video(Video)
    
    var id: UUID {
        switch self {
        case .folder(let folder): return folder.id ?? UUID()
        case .video(let video): return video.id ?? UUID()
        }
    }
    
    var name: String {
        switch self {
        case .folder(let folder): return folder.name ?? ""
        case .video(let video): return video.title ?? ""
        }
    }
    
    var dateCreated: Date {
        switch self {
        case .folder(let folder): return folder.dateCreated ?? Date()
        case .video(let video): return video.dateAdded ?? Date()
        }
    }
    
    var isFolder: Bool {
        if case .folder = self { return true }
        return false
    }
}

// MARK: - Sorting
enum SortOption: String, CaseIterable {
    case nameAscending = "Name A-Z"
    case nameDescending = "Name Z-A"
    case dateCreatedNewest = "Newest First"
    case dateCreatedOldest = "Oldest First"
    case foldersFirst = "Folders First"
}

enum SubtitleFormat: String, CaseIterable {
    case srt = "srt"
    case vtt = "vtt"
    case ssa = "ssa"
    case ass = "ass"
    
    var displayName: String {
        switch self {
        case .srt: return "SubRip (.srt)"
        case .vtt: return "WebVTT (.vtt)"
        case .ssa, .ass: return "SubStation Alpha (.ssa/.ass)"
        }
    }
}

enum VideoFormat: String, CaseIterable {
    case mp4 = "mp4"
    case mov = "mov"
    case m4v = "m4v"
    case mkv = "mkv"
    case avi = "avi"
    case webm = "webm"
    
    static var supportedExtensions: [String] {
        return VideoFormat.allCases.map { $0.rawValue }
    }
}

// MARK: - Library Descriptor (for multiple libraries)
struct LibraryDescriptor: Codable, Identifiable {
    let id: UUID
    let name: String
    let path: URL
    let lastOpenedDate: Date
    let createdDate: Date
    let version: String
    let thumbnailData: Data?
    let videoCount: Int
    let totalSize: Int64
    
    var isAvailable: Bool {
        return FileManager.default.fileExists(atPath: path.path)
    }
    
    var formattedSize: String {
        let formatter = ByteCountFormatter()
        formatter.countStyle = .file
        return formatter.string(fromByteCount: totalSize)
    }
}
